install: ./script/bootstrap

matrix:
  include:
    # lint and build
    - language: ruby
      rvm: 2.4.0
      script: bundle exec rake rubocop build
      env: NAME="Lint and Build"

    # go 1.7 tests
    - language: go
      go: "1.7.x"
      before_script: ./script/source-setup/go
      script: ./script/test go
      env: NAME="go 1.7.x"

    # go 1.10 tests
    - language: go
      go: "1.10.x"
      before_script: ./script/source-setup/go
      script: ./script/test go
      env: NAME="go 1.10.x"

    - language: go
      go: "1.11.1"
      before_script: ./script/source-setup/go
      script: ./script/test go
      env: NAME="go 1.11.1"

    # dep tests
    - language: go
      go: "1.10.x"
      before_script: ./script/source-setup/go
      script: ./script/test dep
      env: NAME="go dep"

    # cabal tests
    - language: haskell
      ghc: "8.2"
      before_script: ./script/source-setup/cabal
      script: ./script/test cabal
      env: NAME="cabal"

    # npm tests
    - language: node_js
      node_js: "8"
      before_script: ./script/source-setup/npm
      script: ./script/test npm
      env: NAME="npm"

    # bower tests
    - language: node_js
      node_js: "8"
      before_script:
        - npm install -g bower
        - ./script/source-setup/bower
      script: ./script/test bower
      env: NAME="bower"

    # bundler tests
    - language: ruby
      rvm: 2.4.0
      before_script: ./script/source-setup/bundler
      script: ./script/test bundler
      env: NAME="bundler"

    # manifest tests
    - language: ruby
      rvm: 2.4.0
      script: ./script/test manifest
      env: NAME="manifest"

    # python 2.7 tests
    - language: python
      python: 2.7
      before_script: ./script/source-setup/pip
      script: ./script/test pip
      env: NAME="pip"

    # python 3.6 tests
    - language: python
      python: 3.6
      before_script: ./script/source-setup/pip
      script: ./script/test pip
      env: NAME="pip"

    - language: python
      python: 3.6
      before_script:
        - pip install pipenv
        - ./script/source-setup/pipenv
      script: ./script/test pipenv
      env: NAME="pipenv"

    - language: ruby
      rvm: 2.4.0
      before_script: ./script/source-setup/git_submodule
      script: ./script/test git_submodule
      env: NAME="git_submodule"

    - language: java
      before_script: ./test/fixtures/gradle/gradlew --quiet --version
      script: ./script/test gradle
      env: NAME="gradle"

notifications:
  disable: true
