name: Create release

on: create

jobs:
  tag_filter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      with:
        args: 'tag'

  package_linux:
    runs-on: ubuntu-latest
    needs: tag_filter

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Build package
      run: script/packages/linux
      env:
        VERSION: ${{github.event.ref}}

    - uses: actions/upload-artifact@master
      with:
        name: licensed-${{github.event.ref}}-linux-x64.tar.gz
        path: pkg/${{github.event.ref}}/licensed-${{github.event.ref}}-linux-x64.tar.gz

  package_mac:
    runs-on: macOS-latest
    needs: tag_filter

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Build package
      run: script/packages/mac
      env:
        VERSION: ${{github.event.ref}}

    - uses: actions/upload-artifact@master
      with:
        name: licensed-${{github.event.ref}}-darwin-x64.tar.gz
        path: pkg/${{github.event.ref}}/licensed-${{github.event.ref}}-darwin-x64.tar.gz
        
  build_gem:
    runs-on: ubuntu-latest
    needs: tag_filter
    
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    
    - name: Build gem
      run: gem build *.gemspec
    
    - uses: actions/upload-artifact@master
      with:
        name: licensed-${{github.event.ref}}.gem
        path: pkg/licensed-${{github.event.ref}}.gem
  
  create_release:
    runs-on: ubuntu-latest
    needs: [package_linux, package_mac, build_gem]
    steps:
    - uses: actions/checkout@master
    - uses: Roang-zero1/github-create-release-action@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
        VERSION_REGEX: "^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+"

  upload_packages:
    runs-on: ubuntu-latest
    needs: [create_release]

    steps:
    - uses: actions/download-artifact@master
      with:
        name: licensed-${{github.event.ref}}-linux-x64.tar.gz
    - uses: actions/download-artifact@master
      with:
        name: licensed-${{github.event.ref}}-darwin-x64.tar.gz

    - name: Publish to GitHub Release
      uses: Roang-zero1/github-upload-release-artifacts-action@v2.0.0
      with:
        args: licensed-${{github.event.ref}}-linux-x64.tar.gz licensed-${{github.event.ref}}-darwin-x64.tar.gz
      env:
        GITHUB_TOKEN: ${{secrets.API_AUTH_TOKEN}}

    - uses: actions/download-artifact@master
      with:
        name: licensed-${{github.event.ref}}.gem

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
